const EMOJIS = [
  { nome: "sorriso", emoji: "😊" },
  { nome: "coracao", emoji: "❤️" },
  { nome: "positivo", emoji: "👍" },
  { nome: "negativo", emoji: "👎" },
  { nome: "risada", emoji: "😂" },
  { nome: "piscada", emoji: "😉" },
  { nome: "choro", emoji: "😢" },
  { nome: "bravo", emoji: "😠" },
  { nome: "surpreso", emoji: "😲" },
  { nome: "pensativo", emoji: "🤔" },
  { nome: "aplauso", emoji: "👏" },
  { nome: "aceno", emoji: "👋" },
  { nome: "olhos", emoji: "👀" },
  { nome: "oracao", emoji: "🙏" },
  { nome: "fogo", emoji: "🔥" },
  { nome: "estrela", emoji: "⭐" },
  { nome: "marcaDeVerificacao", emoji: "✅" },
  { nome: "marcaDeX", emoji: "❌" },
  { nome: "mais", emoji: "➕" },
  { nome: "menos", emoji: "➖" },
  { nome: "pontoDeInterrogacao", emoji: "❓" },
  { nome: "pontoDeExclamacao", emoji: "❗" },
  { nome: "pizza", emoji: "🍕" },
  { nome: "cafe", emoji: "☕" },
  { nome: "cerveja", emoji: "🍺" },
  { nome: "futebol", emoji: "⚽" },
  { nome: "basquete", emoji: "🏀" },
  { nome: "computador", emoji: "💻" },
  { nome: "musica", emoji: "🎵" },
  { nome: "livro", emoji: "📚" },
  { nome: "presente", emoji: "🎁" },
  { nome: "confete", emoji: "🎉" },
  { nome: "balao", emoji: "🎈" },
  { nome: "arvoreDeNatal", emoji: "🎄" },
  { nome: "abobora", emoji: "🎃" },
  { nome: "disfarçado", emoji: "🥸" },
] as const;

export { EMOJIS };
